#! /usr/bin/env python
#  -*- coding: utf-8 -*-
## USANDO ENGINE RATCAVE
# GUI generated by PAGE version 5.4 with Tcl version 8.6
#    Mar 13, 2021 06:29:44 PM -03  platform: Linux
import time
import subprocess
import mido
portmidi = mido.Backend('mido.backends.portmidi')

#INTERFACE/TELA
from tela import *
#FIM INTERFACE/TELA

def load_param(filecfg):#le parametros de um arquivo e devolve em forma de lista
 p=[]					#ignora linhas em branco, mas o 1o caracter da linha nao pode ser espaco
 t=[] 					#lista temporaria
 f= open(filecfg, 'r')
 count = 0
 while True:
  count += 1
  line = f.readline()
  if not line:			# if line is empty
    break; 				# end of file is reached
  if line[0]!='' and line[0]!='\r' and line[0]!='\n' and line[0]!=';':
    sep = line.find('=')  #acha o sinal de igual
    t.append(line[0:sep].strip())
    t.append(line[sep+1:].split(',')[0].strip())
    t.append(line[sep+1:].split(',')[1].strip())
    t.append(line[sep+1:].split(',')[2].strip())
    p.append(t.copy());
    print("Line{}: {}".format(count, line.strip()))
    print(t)
    t.clear();
 print(p)
 f.close()
 return p

#Listando entradas e saidas
saidas=portmidi.get_output_names()
entradas=portmidi.get_input_names()
pass_midi=0;
porta=None
porta2=None
nporta=0
fullwindow=False #a janela 3d
if __name__ == '__main__':
  print('Entradas : '+str(entradas));
  print('Saidas : '+str(saidas));
  vp_start_gui() #abre a interface do keylight
  
  print('entrada ativada '+tela.combobox.get() )
  nporta=entradas.index(tela.combobox.get())
  print('numero da porta : '+str(nporta))
  porta = portmidi.open_input(tela.combobox.get());
  if tela.che52.get()==1:
    pass_midi=tela.che52.get();
    print('saida ativada '+tela.combobox2.get());
    porta2 = portmidi.open_output(tela.combobox2.get());
  if(tela.combobox3.get()=='Bars'):
   anim=1
  elif (tela.combobox3.get()=='Plane'):
   anim=2
  else: anim=1
  if tela.che44.get()==1:
      fullwindow=True
  else: fullwindow=False
  #p=load_param('param.cfg')
  a = open("param.cfg", "w")
  a.write('midiin ='+tela.combobox.get()+'\n')
  a.write('midiout='+str(porta2)+'\n')
  a.write('passmidi='+str(pass_midi)+'\n')
  a.write('fullwin='+str(fullwindow)+'\n')
  a.write('anim   ='+str(anim))
  #os.spawnlp(os.P_WAIT, "teste3", os.environ)
  #subprocess.call("./teste3", shell=True)  #essa funciona!
